// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members






import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrptaw9KS1AJyP21kaaf3jejd4oHgI5HQ',
    appId: '1:160648342535:web:5f2f7fe5c54e4c89558ea2',
    messagingSenderId: '160648342535',
    projectId: 'gomart-358609',
    authDomain: 'gomart-358609.firebaseapp.com',
    storageBucket: 'gomart-358609.appspot.com',
    measurementId: 'G-2HPDGFQXSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBADxFyMGVFFnyTG55TV-_bXgeVRfvn6H4',
    appId: '1:160648342535:android:801488d98457bea5558ea2',
    messagingSenderId: '160648342535',
    projectId: 'gomart-358609',
    storageBucket: 'gomart-358609.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDisnghaBdUlyq_D-7A773Aw5xzaXQ-uOw',
    appId: '1:160648342535:ios:8b969ec5d7071a0e558ea2',
    messagingSenderId: '160648342535',
    projectId: 'gomart-358609',
    storageBucket: 'gomart-358609.appspot.com',
    iosClientId: '160648342535-l5hslejglmnpe40ageh3u1pevvmqjruc.apps.googleusercontent.com',
    iosBundleId: 'com.example.goMartClient',
  );
}
